apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truck-medoc-api-monitor
  namespace: monitoring
  labels:
    app: truck-medoc-api
spec:
  selector:
    matchLabels:
      app: truck-medoc-api
  namespaceSelector:
    matchNames:
    - truck-medoc
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
