apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: truck-medoc
data:
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "molecules"
  API_PORT: "8080"
  LOG_LEVEL: "info"
  ENVIRONMENT: "development"
